version: "3.8"
services:
  jenkins-plugin:
    image: maven:3.8.5-openjdk-17
    ports:
      - "8080:8080"
    volumes:
      - .:/plugin
      - ~/.m2:/root/.m2 # cache maven dependencies
    working_dir: /plugin
    command: mvn hpi:run
