name: Build and Release Plugin

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: "11"
          distribution: "adopt"

      - name: Build with Maven
        run: mvn clean package

      - name: Remove unnecessary files from target
        run: find target -type f ! -name '*.hpi' -delete

      - name: Set HPI file name
        id: set_filename
        run: echo "HPI_FILE_NAME=testkube-cli-setup-${GITHUB_REF#refs/tags/}.hpi" >> $GITHUB_ENV

      - name: Rename HPI file
        run: mv target/*.hpi target/${{ env.HPI_FILE_NAME }}

      - name: List files in target
        run: ls -l target/

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false

      - name: Upload HPI file to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./target/${{ env.HPI_FILE_NAME }}
          asset_name: ${{ env.HPI_FILE_NAME }}
          asset_content_type: application/octet-stream
